services:
  db:
    image: postgres:16.11-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
      start_interval: 5s

  backend:
    image: directus/directus:11.14
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8055:8055
    environment:
      SECRET: ${DIRECTUS_SECRET}

      DB_CLIENT: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}

      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD}

      PUBLIC_URL: https://dndvault.ru
      EMAIL_VERIFY_SETUP: false
      MCP_ENABLED: false

      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "'self' https://dndvault.ru"
      QUERY_LIMIT_MAX: 100
    volumes:
      - uploads:/directus/uploads

  frontend:
    build:
      context: .
      dockerfile: web.Dockerfile
    restart: on-failure
    depends_on:
      - backend

  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    restart: on-failure
    depends_on:
      - frontend
    ports:
      - 10034:10034

volumes:
  postgres-data:
  uploads:
